% Script generated by Brainstorm (12-Dec-2022)

% Input files
sFiles = [];
SubjectNames = {...
    'chan32'};

% Start a new report
bst_report('Start', sFiles);

% Process: Select matrix files in: chan32/NewCondition/sig_final
sFiles = bst_process('CallProcess', 'process_select_files_matrix', sFiles, [], ...
    'subjectname',   SubjectNames, ...
    'condition',     'NewCondition', ...
    'tag',           'sig_final', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
% bst_report('Email', ReportFile, username, to, subject, isFullReport);

